[tool.poetry]
name = "cta-stop-watch"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
datetime = "^5.5"
polars = "^0.20.31"
pathlib = "^1.0.1"
duckdb = "^1.0.0"
pandas = "^2.2.2"
geopandas = "^0.14.4"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
